url: "https://aimnana.github.io"
baseurl: "/fcc-responsive-web-design-projects"

title: "FCC Responsive Web Design"
description: "Portfolio dei progetti realizzati nel percorso FreeCodeCamp • Responsive Web Design."

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Domiziana"
  github: "aimNana"

# Opzionali (migliorano anteprime social/SEO)
#logo: /assets/img/avatar.png        # crea il file se vuoi un’icona
social:
  github: aimNana
