url: "https://aimnana.github.io"
baseurl: "/fcc-responsive-web-design-projects"

title: "FCC Responsive Web Design"
description: "Showcasing my journey through the FreeCodeCamp Responsive Web Design certification."

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap

author:
  name: "Domiziana"
  github: "aimNana"
